# Generated by Django 5.2.7 on 2025-12-25 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], max_length=50)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('platform_user_id', models.CharField(blank=True, help_text='User ID on the platform', max_length=255, null=True)),
                ('platform_username', models.CharField(blank=True, help_text='Username on the platform', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional platform-specific data')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active and can be used')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.AddField(
            model_name='post',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='external_post_id',
            field=models.CharField(blank=True, help_text='ID returned by the platform API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'status'], name='posts_post_user_id_8bb7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['platform', 'status'], name='posts_post_platfor_0c5aca_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['scheduled_time'], name='posts_post_schedul_8e9536_idx'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'platform'], name='posts_socia_user_id_bc6df3_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform', 'is_active'], name='posts_socia_platfor_90a041_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('user', 'platform')},
        ),
    ]
